name: 'Life Productions, Inc.'
favicon: null
layout_spectrum: 0.75511
typography_spectrum: 0.57314
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#90c84b'
    - '#17200c'
    - '#5c8030'
    - '#435d23'
  brandStrength: 0.30200653430074453
  lightness: 0.1672898242250085
  saturation: 0.17943635559640825
  rhythmicContrast: 0.13468212774023414
purpose: []
